import path from 'path';
import { createComponentLogger, Database as TestMindDatabase } from '@testmind/core';
import type { ProjectConfig, TestSuite } from '@testmind/shared';

const logger = createComponentLogger('suite');
const DB_FILE_NAME = 'testmind.db';
const PLACEHOLDER_SUITE_IDS = ['preview-suite-alpha', 'preview-suite-beta', 'preview-suite-gamma'];

export interface ResolveSuitesOptions {
  config: ProjectConfig;
  suiteId?: string;
  limit?: number;
}

const resolveDatabasePath = (config: ProjectConfig): string => {
  const repoPath = config.repoPath || process.cwd();
  return path.join(repoPath, '.testmind', DB_FILE_NAME);
};

const tryWithDatabase = async <T>(
  config: ProjectConfig,
  callback: (db: TestMindDatabase) => Promise<T>
): Promise<T | null> => {
  const dbPath = resolveDatabasePath(config);
  const database = new TestMindDatabase(dbPath);

  try {
    await database.initialize();
    return await callback(database);
  } catch (error) {
    logger.warn('Failed to access TestMind database', {
      error: (error as Error)?.message ?? String(error),
      path: dbPath,
    });
    return null;
  } finally {
    try {
      await database.close();
    } catch (closeError) {
      logger.warn('Failed to close TestMind database', {
        error: (closeError as Error)?.message ?? String(closeError),
        path: dbPath,
      });
    }
  }
};

const buildPlaceholderSuite = (
  suiteId: string,
  config: ProjectConfig,
  label?: string,
): TestSuite => {
  const framework = config.testFramework || 'vitest';
  const id = suiteId || `preview-${label ?? 'suite'}`;

  return {
    id,
    projectId: config.id ?? 'preview-project',
    targetEntityId: label ?? 'preview-intent',
    testType: 'unit',
    framework,
    code: `// Placeholder suite ${id}\n// Generated by CLI preview tooling`,
    filePath: path.join('.testmind', 'preview', `${id}.test.${framework}.ts`),
    generatedAt: new Date(),
    generatedBy: 'ai',
    metadata: {
      preview: true,
      label: label ?? 'CLI preview suite',
      source: 'cli-preview',
    },
  } as TestSuite;
};

const createPreviewSuites = (config: ProjectConfig, limit = 3): TestSuite[] => {
  return Array.from({ length: limit }).map((_, index) =>
    buildPlaceholderSuite(
      PLACEHOLDER_SUITE_IDS[index] ?? `preview-${index + 1}`,
      config,
      `Preview suite ${index + 1}`,
    ),
  );
};

export const resolveSuites = async ({ config, suiteId, limit }: ResolveSuitesOptions): Promise<TestSuite[]> => {
  const fromDb = await tryWithDatabase(config, async (database) => {
    if (suiteId) {
      const suite = await database.getTestSuite(suiteId);
      return suite ? [suite] : [];
    }

    const allSuites = await database.getTestSuitesByProject(config.id);
    if (!allSuites || allSuites.length === 0) {
      return [];
    }

    return typeof limit === 'number' ? allSuites.slice(0, limit) : allSuites;
  });

  if (fromDb && fromDb.length > 0) {
    return fromDb;
  }

  if (suiteId) {
    return [buildPlaceholderSuite(suiteId, config)];
  }

  return createPreviewSuites(config, limit ?? 3);
};

export const resolveSuite = async (config: ProjectConfig, suiteId: string): Promise<TestSuite> => {
  const suites = await resolveSuites({ config, suiteId, limit: 1 });
  if (suites.length > 0) {
    return suites[0];
  }

  return buildPlaceholderSuite(suiteId, config);
};

export const isPreviewSuite = (suite: TestSuite): boolean => Boolean(suite.metadata?.preview === true);
