import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const { mockPrinter, mockGitMethods, mockGitConstructor } = vi.hoisted(() => {
  const mockGitMethods = {
    isGitRepo: vi.fn().mockResolvedValue(true),
    getRecentCommits: vi.fn().mockResolvedValue([{ hash: 'abc123', message: 'Generated by TestMind', date: '2025-01-01', author: 'TestMind' }]),
    isLastCommitFromTestMind: vi.fn().mockResolvedValue(true),
    undoAndDiscard: vi.fn().mockResolvedValue({ success: true, message: 'undone' }),
    undoLastCommit: vi.fn().mockResolvedValue({ success: true, message: 'undone' }),
  };

  return {
    mockPrinter: {
      header: vi.fn(),
      error: vi.fn(),
      warn: vi.fn(),
      status: vi.fn(),
      section: vi.fn(),
      success: vi.fn(),
      info: vi.fn(),
      list: vi.fn(),
      keyValue: vi.fn(),
      nextSteps: vi.fn(),
      blank: vi.fn(),
    },
    mockGitMethods,
    mockGitConstructor: vi.fn(() => mockGitMethods),
  };
});

vi.mock('../ui/stdoutPrinter', () => ({
  createStdoutPrinter: () => mockPrinter,
}));

vi.mock('@testmind/core', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@testmind/core')>();
  return {
    ...actual,
    GitAutomation: mockGitConstructor,
  };
});

import { undoLastCommit } from '../commands/undo';

describe('undoCommand', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockPrinter.header.mockClear();
    process.exitCode = undefined;
    mockGitConstructor.mockClear();
  });

  afterEach(() => {
    process.exitCode = undefined;
  });

  it('requires --experimental to run undo', async () => {
    mockGitMethods.isGitRepo.mockResolvedValue(true);

    await undoLastCommit({ skipExit: true });

    expect(mockPrinter.warn).toHaveBeenCalledWith(expect.stringContaining('experimental'));
    expect(process.exitCode).toBe(1);
    expect(mockGitConstructor).toHaveBeenCalledOnce();
  });

  it('shows preview plan when not confirmed', async () => {
    mockGitMethods.isGitRepo.mockResolvedValue(true);
    mockGitMethods.isLastCommitFromTestMind.mockResolvedValue(true);

    await undoLastCommit({ experimental: true, showHistory: true, skipExit: true });

    expect(mockPrinter.section).toHaveBeenCalledWith(
      'Undo plan',
      expect.arrayContaining([expect.stringContaining('target commit: abc123')]),
    );
    expect(mockPrinter.status).toHaveBeenCalledWith(
      'Preview',
      expect.stringContaining('Add --confirm'),
    );
    expect(mockGitMethods.undoLastCommit).not.toHaveBeenCalled();
    expect(process.exitCode).toBe(0);
  });

  it('executes soft undo when confirmed', async () => {
    mockGitMethods.isGitRepo.mockResolvedValue(true);
    mockGitMethods.isLastCommitFromTestMind.mockResolvedValue(false);

    await undoLastCommit({ experimental: true, confirm: true, skipExit: true });

    expect(mockGitMethods.undoLastCommit).toHaveBeenCalled();
    expect(mockGitMethods.undoAndDiscard).not.toHaveBeenCalled();
    expect(mockPrinter.warn).toHaveBeenCalledWith(
      expect.stringContaining('not created by TestMind'),
    );
  });

  it('runs hard undo when requested', async () => {
    mockGitMethods.isGitRepo.mockResolvedValue(true);

    await undoLastCommit({ experimental: true, confirm: true, hard: true, skipExit: true });

    expect(mockGitMethods.undoAndDiscard).toHaveBeenCalled();
  });
});
