name: 🐛 Bug Report
description: Report a bug in TestMind
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I run testmind generate..., it fails with...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'testmind generate src/utils/math.ts'
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen
      placeholder: Should generate test file successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
      placeholder: Got error message...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - TestMind version: [e.g. v0.4.0-alpha]
        - Node version: [e.g. 20.10.0]
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - LLM provider: [e.g. OpenAI, Gemini, Ollama]
        - Test framework: [e.g. vitest, jest]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: If applicable, add logs or error messages
      placeholder: Paste error messages or logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: This started happening after...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true

description: Report a bug in TestMind
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I run testmind generate..., it fails with...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'testmind generate src/utils/math.ts'
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen
      placeholder: Should generate test file successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
      placeholder: Got error message...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - TestMind version: [e.g. v0.4.0-alpha]
        - Node version: [e.g. 20.10.0]
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - LLM provider: [e.g. OpenAI, Gemini, Ollama]
        - Test framework: [e.g. vitest, jest]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: If applicable, add logs or error messages
      placeholder: Paste error messages or logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: This started happening after...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true

description: Report a bug in TestMind
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I run testmind generate..., it fails with...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'testmind generate src/utils/math.ts'
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen
      placeholder: Should generate test file successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
      placeholder: Got error message...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - TestMind version: [e.g. v0.4.0-alpha]
        - Node version: [e.g. 20.10.0]
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - LLM provider: [e.g. OpenAI, Gemini, Ollama]
        - Test framework: [e.g. vitest, jest]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: If applicable, add logs or error messages
      placeholder: Paste error messages or logs here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: This started happening after...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all required information above
          required: true

