import { describe, expect, afterEach, it } from 'vitest';

import type { TestSkill, TestSuite, ValidationResult } from '@testmind/shared';

import { SkillRegistry } from '../SkillRegistry';

const createTestSkill = (name: string): TestSkill => ({
  metadata: {
    name,
    version: '0.0.1',
    description: 'stub skill for feature flag tests',
    author: 'test-suite',
    supportedFrameworks: ['vitest'],
    supportedLanguages: ['typescript'],
  },
  canHandle: () => true,
  generateTest: async () =>
    ({
      id: `${name}-suite`,
      projectId: 'demo',
      targetEntityId: 'demo-entity',
      testType: 'unit',
      framework: 'vitest',
      code: '// generated by stub',
      filePath: 'tests/demo.spec.ts',
      generatedAt: new Date('2024-01-01T00:00:00.000Z'),
      generatedBy: 'ai',
      metadata: {},
    }) as TestSuite,
  validateTest: async (): Promise<ValidationResult> => ({
    valid: true,
    issues: [],
  }),
});

afterEach(() => {
  delete process.env.SKILL_ADAPTER_EXPERIMENTAL;
});

describe('SkillRegistry feature flag integration', () => {
  it('enables skills that are explicitly whitelisted', () => {
    process.env.SKILL_ADAPTER_EXPERIMENTAL = 'alpha-skill';

    const registry = new SkillRegistry();
    const allowedSkill = createTestSkill('alpha-skill');
    registry.registerTestSkill(allowedSkill);

    expect(registry.isSkillEnabled('alpha-skill')).toBe(true);
  });

  it('disables skills that are not in the allow list', () => {
    process.env.SKILL_ADAPTER_EXPERIMENTAL = 'beta-skill';

    const registry = new SkillRegistry();
    const blockedSkill = createTestSkill('gamma-skill');
    registry.registerTestSkill(blockedSkill);

    expect(registry.isSkillEnabled('gamma-skill')).toBe(false);
  });
});
