import type {
  TestContext,
  TestSkill,
  TestSuite,
  ValidationResult,
} from '@testmind/shared';
import { describe, expect, it } from 'vitest';

import { BaseSkill, type SkillContext, type SkillResult } from '../Skill';
import { SkillRegistry } from '../SkillRegistry';

class LegacyEchoSkill extends BaseSkill {
  readonly name = 'legacy-echo';
  readonly description = 'Echoes prompt metadata to verify legacy Skill contracts';
  readonly category = 'testing' as const;
  readonly version = '0.0.1';

  canHandle(context: SkillContext): boolean {
    return context.userPrompt.toLowerCase().includes('echo');
  }

  async execute(context: SkillContext): Promise<SkillResult> {
    return this.success('legacy-executed', [], {
      prompt: context.userPrompt,
      files: context.targetFiles,
    });
  }
}

const createAdaptedTestSkill = (name: string): TestSkill => ({
  metadata: {
    name,
    version: '0.0.1',
    description: 'adapter contract test skill',
    author: 'contracts',
    supportedFrameworks: ['vitest'],
    supportedLanguages: ['typescript'],
  },
  canHandle: () => true,
  async generateTest(context: TestContext): Promise<TestSuite> {
    return {
      id: `${name}-suite`,
      projectId: context.projectId ?? 'demo',
      targetEntityId: context.filePath ?? 'demo.ts',
      testType: context.testType ?? 'unit',
      framework: context.framework ?? 'vitest',
      code: '// generated by adapter contract test',
      filePath: context.filePath ?? 'demo.contract.spec.ts',
      generatedAt: new Date('2024-01-01T00:00:00.000Z'),
      generatedBy: 'ai',
      metadata: {},
    };
  },
  async validateTest(): Promise<ValidationResult> {
    return { valid: true, issues: [] };
  },
});

describe('SkillRegistry contracts', () => {
  it('registers legacy Skill implementations and exposes them via findSkillsForContext', async () => {
    const registry = new SkillRegistry();
    const skill = new LegacyEchoSkill();
    registry.register(skill);

    const context: SkillContext = {
      projectPath: process.cwd(),
      projectConfig: {},
      targetFiles: ['src/echo.ts'],
      userPrompt: 'please echo this input',
    };

    const matches = await registry.findSkillsForContext(context);
    expect(matches).toHaveLength(1);
    const result = await matches[0]!.execute(context);
    expect(result.success).toBe(true);
    expect(result.metadata?.prompt).toContain('echo');
  });

  it('adapts new TestSkill implementations through registerTestSkill', async () => {
    const registry = new SkillRegistry();
    registry.registerTestSkill(createAdaptedTestSkill('adapter-contract'), {
      enable: true,
    });

    const context: SkillContext = {
      projectPath: process.cwd(),
      projectConfig: {},
      targetFiles: ['src/contract.ts'],
      userPrompt: 'generate a contract test',
      framework: 'vitest',
      testType: 'unit',
    };

    const matches = await registry.findSkillsForContext(context);
    expect(matches).toHaveLength(1);
    const execution = await matches[0]!.execute(context);
    expect(execution.success).toBe(true);
    expect(execution.message).toMatch(/adapter/i);
  });

  it('rejects malformed TestSkill registrations', () => {
    const registry = new SkillRegistry();
    const invalidSkill = {
      metadata: {
        name: 'invalid',
        version: '0.0.1',
        description: 'missing frameworks and languages',
        author: 'bad-actor',
        supportedFrameworks: [],
        supportedLanguages: [],
      },
      canHandle: () => true,
      async generateTest(): Promise<TestSuite> {
        throw new Error('should not execute');
      },
      async validateTest(): Promise<ValidationResult> {
        return { valid: true, issues: [] };
      },
    } satisfies TestSkill;

    expect(() => registry.registerTestSkill(invalidSkill, { enable: true })).toThrow(
      /Cannot register invalid TestSkill/i,
    );
  });

  it('does not surface disabled TestSkill entries until they are explicitly enabled', async () => {
    const registry = new SkillRegistry();
    const name = 'disabled-adapter';
    registry.registerTestSkill(createAdaptedTestSkill(name), { enable: false });

    const context: SkillContext = {
      projectPath: process.cwd(),
      projectConfig: {},
      targetFiles: ['src/adapter.ts'],
      userPrompt: 'try adapter skill',
      framework: 'vitest',
      testType: 'unit',
    };

    const matchesWhileDisabled = await registry.findSkillsForContext(context);
    expect(matchesWhileDisabled).toHaveLength(0);
    expect(registry.isSkillEnabled(name)).toBe(false);

    registry.enable(name);

    const matchesAfterEnable = await registry.findSkillsForContext(context);
    expect(matchesAfterEnable).toHaveLength(1);
    const execution = await matchesAfterEnable[0]!.execute(context);
    expect(execution.success).toBe(true);
    expect(execution.message).toMatch(/generated via disabled-adapter/i);
  });
});
